name: hypersend 
description: "Hypersend - Fast. Secure. Chat."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Routing
  go_router: ^14.6.2
  
  # API & Network
  dio: ^5.7.0
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  file_picker: ^8.1.7
  crypto: ^3.0.6
  url_launcher: ^6.1.0
  path_provider: ^2.1.4
  
  # Security & Encryption
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  flutter_secure_storage: ^9.2.2
  
  # Device Info & Database
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  sqflite: ^2.4.1
  path: ^1.9.0
  
  # Analytics
  firebase_analytics: ^11.2.0
  firebase_core: ^3.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Internationalization
  generate: true

  assets:
    - assets/
    - assets/icons/